# Import Data & Data Cleaning

## Load required libraries

```{r}
library(tidyverse)
library(plm)
library(readxl)
library(fastDummies)
library(car)
library(nlme)
library(MASS)
library(lmtest)
```

## Data Cleaning

```{r}
df<- read_xlsx('database2010_2019_Febcorrect3_ALBERT.xlsx') %>%
        dplyr::select(AIRCRAFT_TYPE, ln_AIR_FUELS_ISSUED,
        ln_DEPARTURES_PERFORMED, ln_AIR_TIME, ln_DISTANCE,
        ln_PAYLOAD, time, AIRLINE_ID) %>%
  dplyr::mutate(AIRCRAFT_TYPE=dplyr::recode(AIRCRAFT_TYPE, '612'='B737-700', '614'='B737-800', '634'='B737-900','698'='A319', '694'='A320', '622'='B757-200','626'='B767-300', '627'='B777','637'='B777')) %>%
  group_by(AIRCRAFT_TYPE, time, AIRLINE_ID) %>%
  summarise(ln_AIR_FUELS_ISSUED = log(sum(exp(ln_AIR_FUELS_ISSUED))),
            ln_DEPARTURES_PERFORMED = log(sum(exp(ln_DEPARTURES_PERFORMED))),
            ln_AIR_TIME = log(sum(exp(ln_AIR_TIME))),
            ln_DISTANCE = log(sum(exp(ln_DISTANCE))),
            ln_PAYLOAD = log(sum(exp(ln_PAYLOAD))))
df <- subset(df, !is.na(AIRCRAFT_TYPE))
```



```{r}
# Load ppi data and recode the month into quarters and calculate the inflation rate (ratio)
ppi<- read_csv('ppi.csv') %>%
  pivot_longer(-Year, names_to = 'Month', values_to = 'ppi') %>%
  mutate(quarter=ifelse(Month %in% c('Jan', 'Feb', 'Mar'), 'Q1', 
                        ifelse(Month %in% c('Apr', 'May', 'Jun'), 'Q2',
                               ifelse(Month %in% c('Jul', 'Aug', 'Sep'), 'Q3', 'Q4')))) %>%
  group_by(Year, quarter) %>%
  summarise(ppi=mean(ppi)) %>%
  arrange(Year, quarter) %>%
  ungroup() %>%
  mutate(time=row_number(),
         ratio=ppi/173)

# Load fuel price
fuel_price<- read_xlsx('all_flights_fuel.xlsx') %>% 
  dplyr::select(time,`ln_Average_Fuel_Price (Dollar per gallon)`) %>%
  unique()

# Merge all data set together and calculate the aggregated y and x variables
aggregated_data <- df %>%
  left_join(fuel_price, by='time') %>%
  left_join(ppi %>% dplyr::select(time, ratio), 'time') %>%
  mutate(`ln_Average_Fuel_Price (Dollar per gallon)` = log(exp(`ln_Average_Fuel_Price (Dollar per gallon)`) / ratio))
```



```{r}
aircraft_counts <- aggregated_data %>%
  group_by(AIRCRAFT_TYPE) %>%
  summarise(Count = n())
aircraft_counts
```



```{r}
# Recode column names
colnames(aggregated_data)<- c('aircraft_type', 'time' ,'airline_id', 'ln_fuel', 'ln_number_of_flights', 'ln_airborne_hours', 'ln_distance', 'ln_payload', 'ln_average_fuel_price', 'ratio')
aggregated_data <- subset(aggregated_data, select = -c(ratio))
aggregated_data
```


```{r}
for(i in 1:8){
  ln_fuel_i<- aggregated_data %>%
    mutate(time=time+i, fpt=ln_average_fuel_price) %>%
    dplyr::select(aircraft_type, time, fpt) %>%
    unique()

  aggregated_data<- aggregated_data %>%
    left_join(ln_fuel_i, by=c('aircraft_type','time'))
}

aggregated_data<- aggregated_data %>%
  mutate(quater = ifelse(time%%4==0, 4, time%%4))
colnames(aggregated_data)[11:length(colnames(aggregated_data))-1] <- unlist(lapply(1:8, function(x) paste0('ln_fuel_price_t_minus_', x)))
```

```{r}
airline_id<- read_csv('airline_id.csv')
colnames(airline_id)<- c('airline_id', 'name')
  
aggregated_data<- airline_id %>% 
  right_join(aggregated_data, by='airline_id')

names<- unlist(strsplit(aggregated_data$name, ': '))
names<- names[seq(2, length(names),2)]
names<- substr(names,1,2)


aggregated_data$name<- as.factor(names)
```
```{r}
fuel_lag<- colnames(aggregated_data)[10:17]
aggregated_data
```



```{r}

selected_id<- aggregated_data %>%
  group_by(name, aircraft_type) %>%
  summarise(n=n()) %>%
  filter(n>2) 


df<- aggregated_data %>%
  filter(name %in% selected_id$name, aircraft_type %in% selected_id$aircraft_type)

pdf<- aggregated_data
pdf$id<- paste0(pdf$name, pdf$aircraft_type)
pdf<- pdata.frame(pdf, index=c('id', 'time'))

sum1<- summary(plm(lm_form, pdf, model='pooling', effect='twoways'))

x<- sum1$residuals
y<- lag(sum1$residuals)


lm_form<- ln_fuel ~ ln_number_of_flights + ln_airborne_hours + ln_distance + ln_payload + ln_average_fuel_price + ln_fuel_price_t_minus_1
lm_model<- lm(lm_form, data=df)
summary(lm_model)


library(lme4)
formula<- ln_fuel ~ ln_number_of_flights + ln_airborne_hours + ln_distance + ln_payload + ln_average_fuel_price + ln_fuel_price_t_minus_1 + as.factor(quater) + (1|airline_id) + (1|aircraft_type) + (1|time)
model<- lmer(formula, data=df)
summary(model)
```



# Regression
## Helper Functions

```{r}
calc_stats<- function(model, almon, indent=3){
  m<- summary(model)
  sse<- m$ssr
  sst<- m$tss
  n<- m$df.residual+length(m$coefficients)
  k<- length(m$coefficients)+1
  
  num<- sse/(n-k)
  d<- sst/(n-1)
  adjust_r_square<- 1- num/d
  
  rmse<- sqrt(sse/n)
  AIC<- n * log(sse/n) + 2*k
  
  print(paste0('adjusted rsqured: ', adjust_r_square))
  print(paste0('AIC: ', AIC))
  print(paste0('rmse: ', rmse))
  print(paste0('scaling coefficient: ', sum(m$coefficients[2:5])))
  
  vcov_matrix<- vcov(model)
  coefficient<- coef(model)
  
  grad<- rep(0, length(coefficient))
  grad[2:5]<- 1
  se<- sqrt(t(grad)%*%vcov_matrix%*%grad)
  print(paste0('scaling coefficient se: ', se))
  
  if(almon==FALSE){
   # A<- diag(1, length(coefficient)-5)
    A<- diag(1, length(coefficient)-5-indent)
  }else{
    A<- almon
  }


 # fuel_price_coef<- m$coefficients[6:length(m$coefficients)]

  fuel_price_coef<- m$coefficients[(6+indent):length(m$coefficients)]
  

  
  print(A)
  print(fuel_price_coef)
  fuel_price_coef<- A %*% fuel_price_coef
  print('fuel price lag coefficient')
  print(fuel_price_coef)
  print(paste0('fuel price combined effects: ', sum(fuel_price_coef)))
  
  #vcov_matrix_fuel_price<- vcov_matrix[6:nrow(vcov_matrix), 6:nrow(vcov_matrix)]


  vcov_matrix_fuel_price<- vcov_matrix[(6+indent):nrow(vcov_matrix), (6+indent):nrow(vcov_matrix)]

  
  
  vcov_matrix_fuel_price<- A%*%vcov_matrix_fuel_price%*%t(A)
  grad<- rep(1, nrow(vcov_matrix_fuel_price))
  se<- sqrt(t(grad)%*%vcov_matrix_fuel_price%*%grad)
  print(paste0('fuel price combined effect se: ', se))
}


get_A_matrix<- function(order, k){
  A<- matrix(0, nrow=k+1, ncol=order+1)
  for(i in 0:k){
    A[i+1,]<- sapply(0:order, function(p) i^p)
  }
  A
}

almon_lag<- function(data, A){
  k<- nrow(A)-1  
  
  X<- data %>% 
    dplyr::select(ln_average_fuel_price, ln_fuel_price_t_minus_1, ln_fuel_price_t_minus_2, ln_fuel_price_t_minus_3, ln_fuel_price_t_minus_4) %>%
    as.matrix()
  almon_df<- as.data.frame(X[1:nrow(X),1:nrow(A)] %*% A)
  
  data<- cbind(data, almon_df)
 
  data
}
```

## Dataset Filtering

```{r}
aggregated_data_panel<- aggregated_data
aggregated_data_panel$id<- paste0(aggregated_data_panel$name, aggregated_data_panel$aircraft_type)
panel_df<- pdata.frame(aggregated_data_panel, index=c('id', 'time'))

lag<- dplyr::lag
panel_df<- pdata.frame(aggregated_data_panel %>% 
  filter(!is.na(ln_fuel_price_t_minus_4)), index=c('id', 'time'))

selected_id<- panel_df %>%
  group_by(id) %>%
  summarise(n=n()) %>%
  filter(n>2) 


panel_df<- panel_df %>%
  filter(id %in% selected_id$id)
```



```{r}

panel_df

```
```{r}
run_regression<- function(input_df, form, estimation, order, k, oc=FALSE, indent=3){
  if(k < order){
    stop('k must be greater than order')
  }
  
  A<- get_A_matrix(order, k)
  input_df<- pdata.frame(almon_lag(input_df, A), index=c('id', 'time'))
  
  print(colnames(input_df))
  
  # Check if using OLS vs GLS
  bm<- plm(form, input_df)
  print('Checking if need to use GLS')
  print(bptest(bm))

  bm_r<- pggls(form, input_df, model='pooling')

  # Implement OC correction
  error_df = data.frame(bm_r$residuals)
  colnames(error_df)<- 'residuals'
  error_df$index = rownames(error_df)
  
  ocbm<- input_df %>%
    mutate(index=rownames(input_df)) %>%
    left_join(error_df, by='index') %>%
    group_by('name', 'aircraft_type') %>%
    mutate(prev_val = lag(residuals, 1),
           ln_fuel_lag = lag(ln_fuel, 1),
           ln_number_of_flights_lag = lag(ln_number_of_flights, 1),
           ln_airborne_hours_lag = lag(ln_airborne_hours, 1),
           ln_payload_lag = lag(ln_payload, 1),
           ln_distance_lag = lag(ln_distance, 1))
  
  if(order == 0){
    ocbm<- ocbm %>%
      group_by('name', 'aircraft_type') %>%
      mutate(V1_lag = lag(V1, 1))
  }else if(order == 1){
    ocbm<- ocbm %>%
      group_by('name', 'aircraft_type') %>%
      mutate(V1_lag = lag(V1, 1),
             V2_lag = lag(V2, 1))
  }else if(order == 2){
    ocbm<- ocbm %>%
      group_by('name', 'aircraft_type') %>%
      mutate(V1_lag = lag(V1, 1),
             V2_lag = lag(V2, 1),
             V3_lag = lag(V3, 1))
  }else if(order == 3){
    ocbm<- ocbm %>%
      group_by('name', 'aircraft_type') %>%
      mutate(V1_lag = lag(V1, 1),
             V2_lag = lag(V2, 1),
             V3_lag = lag(V3, 1),
             V4_lag = lag(V4, 1))
  }else if(order == 4){
    ocbm<- ocbm %>%
      group_by('name', 'aircraft_type') %>%
      mutate(V1_lag = lag(V1, 1),
             V2_lag = lag(V2, 1),
             V3_lag = lag(V3, 1),
             V4_lag = lag(V4, 1),
             V5_lag = lag(V5, 1))
  }
  
  oc_correct_lm_bm<- lm(residuals~prev_val - 1, data=ocbm)
  rbm<- oc_correct_lm_bm$coefficients
  
  # Turn OC correction off
  if(oc==FALSE){
    rbm<- 0
  }

  ocbm<- ocbm %>%
    mutate(ln_fuel = ln_fuel - rbm * ln_fuel_lag, 
           ln_number_of_flights = ln_number_of_flights - rbm * ln_number_of_flights_lag,
           ln_airborne_hours = ln_airborne_hours - rbm * ln_airborne_hours_lag,
           ln_payload = ln_payload - rbm * ln_payload_lag,
           ln_distance = ln_distance - rbm * ln_distance_lag)
  
  if (order == 0){
    ocbm<- ocbm %>%
      mutate(V1 = V1 - rbm * V1_lag)
  }else if(order == 1){
    ocbm<- ocbm %>%
      mutate(V1 = V1 - rbm * V1_lag,
             V2 = V2 - rbm * V2_lag)
  }else if(order == 2){
    ocbm<- ocbm %>%
      mutate(V1 = V1 - rbm * V1_lag,
             V2 = V2 - rbm * V2_lag,
             V3 = V3 - rbm * V3_lag)
  }else if(order == 3){
    ocbm<- ocbm %>%
      mutate(V1 = V1 - rbm * V1_lag,
             V2 = V2 - rbm * V2_lag,
             V3 = V3 - rbm * V3_lag,
             V4 = V4 - rbm * V4_lag)
  }else if(order == 4){
    ocbm<- ocbm %>%
      mutate(V1 = V1 - rbm * V1_lag,
             V2 = V2 - rbm * V2_lag,
             V3 = V3 - rbm * V3_lag,
             V4 = V4 - rbm * V4_lag,
             V5 = V5 - rbm * V5_lag)
  }
  
  ocbm<- pdata.frame(ocbm, index=c('id', 'time'))
  
  bm_r<- pggls(form, data=ocbm, model='pooling')
  print(summary(bm_r))

  calc_stats(bm_r, A)
  return(bm_r)
}
```

## Incorporating Almon Distributed Lags

```{r}


# Check if FE vs RE
# phtest(form, input_df)
  
# Check if needing OC correction
# dwtest(form, input_df)
  
m1<- run_regression(panel_df, ln_fuel ~ ln_number_of_flights + ln_airborne_hours + ln_payload + ln_distance + as.factor(quater) + V1 + V2, order=1, k=3, indent=3, oc=F)


plot(m1$residuals, lag(m1$residuals, 1), main='Residuals vs Residuals Lag 1 (Order=1, K=3, GLS+ALMON)', xlab='Residuals', ylab='Residuals Lag 1')

```


## Check the structure of heteroscedacity

```{r}

formula <- ln_fuel ~ ln_number_of_flights + ln_airborne_hours + ln_distance + ln_payload + as.factor(quater) +  ln_average_fuel_price + ln_fuel_price_t_minus_1 

plm_model <- plm(formula, data = panel_df, index = c("id", "time"), model = "within")
panel_df$residuals <- residuals(plm_model)

vcov_cluster_both <- vcovHC(plm_model, type = "HC1", cluster = c("group", "time"))
summary(plm_model, vcov = vcov_cluster_both)


# Calculate variance of residuals within each group
group_variances <- tapply(panel_df$residuals, panel_df$id, var)
plot(group_variances, main = "Variance of residuals within each group", xlab = "Group", ylab = "Variance")


time_variances <- tapply(panel_df$residuals, panel_df$time, var)
plot(time_variances, main = "Variance of residuals within each time period", xlab = "Time", ylab = "Variance")
```
```{r}
calc_stats_for_ols<- function(m){

  sse<- sum(m$residuals^2)
  n<- m$df[1] + m$df[2]
  k<- m$df[2]

  
  rmse<- sqrt(sse/n)
  AIC<- n * log(sse/n) + 2*k
  
  
  print(paste0('adjusted rsqured: ', m$r.squared[2]))
  print(paste0('AIC: ', AIC))
  print(paste0('rmse: ', rmse))
  print(paste0('scaling coefficient: ', sum(m$coefficients[,1][1:4])))
  
  grad<- rep(0, length(m$coefficients[,1]))
  grad[1:4]<- 1
  vcov<- m$vcov
  se<- sqrt(t(grad)%*%vcov%*%grad)
  print(paste0('scaling coefficient se: ', se))
  
  
  print(paste0('fuel price combined effect: ', sum(m$coefficients[,1][8:length(m$coefficients[,1])])))
  grad<- rep(0, length(m$coefficients[,1]))
  grad[8:length(m$coefficients[,1])]<- 1
  se<- sqrt(t(grad)%*%vcov%*%grad)
  print(paste0('fuel price combined effect se: ', se))
}

```

## benchmark case 1:

```{r}
input_df<- panel_df
form1<- ln_fuel ~ ln_number_of_flights + ln_airborne_hours + ln_payload + ln_distance + as.factor(quater) + ln_average_fuel_price

# Check if using OLS vs GLS
bm<- plm(form1, data=input_df)
bptest(bm)

# Check if FE vs RE
phtest(form1, input_df)
bm_r<- pggls(form1, data=input_df, model='pooling')
bm_r<- plm(form1, input_df, index = c("id", "time"), model = "within")

# Check if needing OC correction
dwtest(form1, data=input_df)

# Implement OC correction
error_df = data.frame(bm_r$residuals)
colnames(error_df)<- 'residuals'
error_df$index = rownames(error_df)

ocbm<- input_df %>%
  mutate(index=rownames(input_df)) %>%
  left_join(error_df, 'index') %>%
  group_by('name', 'aircraft_type') %>%
  mutate(prev_val = lag(residuals, 1),
         ln_fuel_lag = lag(ln_fuel, 1),
         ln_number_of_flights_lag = lag(ln_number_of_flights, 1),
         ln_airborne_hours_lag = lag(ln_airborne_hours, 1),
         ln_payload_lag = lag(ln_payload, 1),
         ln_distance_lag = lag(ln_distance, 1),
         ln_average_fuel_price_lag = lag(ln_average_fuel_price, 1))

oc_correct_lm_bm<- lm(residuals~prev_val - 1, data=ocbm)
rbm<- oc_correct_lm_bm$coefficients

ocbm<- ocbm %>%
  mutate(ln_fuel = ln_fuel - rbm * ln_fuel_lag, 
         ln_number_of_flights = ln_number_of_flights - rbm * ln_number_of_flights_lag,
         ln_airborne_hours = ln_airborne_hours - rbm * ln_airborne_hours_lag,
         ln_payload = ln_payload - rbm * ln_payload_lag,
         ln_distance = ln_distance - rbm * ln_distance_lag,
         ln_average_fuel_price = ln_average_fuel_price - rbm * ln_average_fuel_price_lag)

ocbm<- pdata.frame(ocbm, index=c('id', 'time'))


bm_r<- pggls(form1, data=ocbm, model='pooling')
bm_r<- plm(form1, ocbm, index = c("id", "time"), model = "within")
summary(bm_r, vcov=vcovHC(bm_r, type="HC1"))
calc_stats_for_ols(summary(bm_r, vcov=vcovHC(bm_r, type="HC1")))
#calc_stats(bm_r, estimate = 'OLS', almon = FALSE)
```





## benchmark case 2:

```{r}
input_df<- panel_df
form1<- ln_fuel ~ ln_number_of_flights + ln_airborne_hours + ln_payload + ln_distance + as.factor(quater) +  ln_average_fuel_price + ln_fuel_price_t_minus_1

# Check if using OLS vs GLS
bm<- plm(form1, data=input_df)
bptest(bm)

# Check if FE vs RE
phtest(form1, input_df)
bm_r<- pggls(form1, data=input_df, model='pooling')
bm_r<- plm(form1, input_df, index = c("id", "time"), model = "within")

# Check if needing OC correction
dwtest(form1, data=panel_df)

# Implement OC correction
error_df = data.frame(bm_r$residuals)
colnames(error_df)<- 'residuals'
error_df$index = rownames(error_df)

ocbm<- input_df %>%
  mutate(index=rownames(input_df)) %>%
  left_join(error_df, 'index') %>%
  group_by('name', 'aircraft_type') %>%
  mutate(prev_val = lag(residuals, 1),
         ln_fuel_lag = lag(ln_fuel, 1),
         ln_number_of_flights_lag = lag(ln_number_of_flights, 1),
         ln_airborne_hours_lag = lag(ln_airborne_hours, 1),
         ln_payload_lag = lag(ln_payload, 1),
         ln_distance_lag = lag(ln_distance, 1),
         ln_average_fuel_price_lag = lag(ln_average_fuel_price, 1),
         ln_fuel_price_t_minus_1_lag = lag(ln_fuel_price_t_minus_1, 1))

oc_correct_lm_bm<- lm(residuals~prev_val - 1, data=ocbm)
rbm<- oc_correct_lm_bm$coefficients

ocbm<- ocbm %>%
  mutate(ln_fuel = ln_fuel - rbm * ln_fuel_lag, 
         ln_number_of_flights = ln_number_of_flights - rbm * ln_number_of_flights_lag,
         ln_airborne_hours = ln_airborne_hours - rbm * ln_airborne_hours_lag,
         ln_payload = ln_payload - rbm * ln_payload_lag,
         ln_distance = ln_distance - rbm * ln_distance_lag,
         ln_average_fuel_price = ln_average_fuel_price - rbm * ln_average_fuel_price_lag,
         ln_fuel_price_t_minus_1 = ln_fuel_price_t_minus_1 - rbm * ln_fuel_price_t_minus_1_lag)

ocbm<- pdata.frame(ocbm, index=c('id', 'time'))


bm_r<- pggls(form1, data=ocbm, model='pooling')
bm_r<- plm(form1, ocbm, index = c("id", "time"), model = "within")
summary(bm_r, vcov=vcovHC(bm_r, type="HC1"))
calc_stats_for_ols(summary(bm_r, vcov=vcovHC(bm_r, type="HC1")))
```


## benchmark case 3:

```{r}
input_df<- panel_df
form1<- ln_fuel ~ ln_number_of_flights + ln_airborne_hours + ln_payload + ln_distance + as.factor(quater) + ln_average_fuel_price + ln_fuel_price_t_minus_1 + ln_fuel_price_t_minus_2

# Check if using OLS vs GLS
bm<- plm(form1, data=input_df)
bptest(bm)

# Check if FE vs RE
phtest(form1, input_df)
bm_r<- pggls(form1, data=input_df, model='pooling')
bm_r<- plm(form1, input_df, index = c("id", "time"), model = "within")

# Check if needing OC correction
dwtest(form1, data=input_df)

# Implement OC correction
error_df = data.frame(bm_r$residuals)
colnames(error_df)<- 'residuals'
error_df$index = rownames(error_df)

ocbm<- input_df %>%
  mutate(index=rownames(input_df)) %>%
  left_join(error_df, 'index') %>%
  group_by('name', 'aircraft_type') %>%
  mutate(prev_val = lag(residuals, 1),
         ln_fuel_lag = lag(ln_fuel, 1),
         ln_number_of_flights_lag = lag(ln_number_of_flights, 1),
         ln_airborne_hours_lag = lag(ln_airborne_hours, 1),
         ln_payload_lag = lag(ln_payload, 1),
         ln_distance_lag = lag(ln_distance, 1),
         ln_average_fuel_price_lag = lag(ln_average_fuel_price, 1),
         ln_fuel_price_t_minus_1_lag = lag(ln_fuel_price_t_minus_1, 1),
         ln_fuel_price_t_minus_2_lag = lag(ln_fuel_price_t_minus_2, 1))

oc_correct_lm_bm<- lm(residuals~prev_val - 1, data=ocbm)
rbm<- oc_correct_lm_bm$coefficients


ocbm<- ocbm %>%
  mutate(ln_fuel = ln_fuel - rbm * ln_fuel_lag, 
         ln_number_of_flights = ln_number_of_flights - rbm * ln_number_of_flights_lag,
         ln_airborne_hours = ln_airborne_hours - rbm * ln_airborne_hours_lag,
         ln_payload = ln_payload - rbm * ln_payload_lag,
         ln_distance = ln_distance - rbm * ln_distance_lag,
         ln_average_fuel_price = ln_average_fuel_price - rbm * ln_average_fuel_price_lag,
         ln_fuel_price_t_minus_1 = ln_fuel_price_t_minus_1 - rbm * ln_fuel_price_t_minus_1_lag,
         ln_fuel_price_t_minus_2 = ln_fuel_price_t_minus_2 - rbm * ln_fuel_price_t_minus_2_lag)

ocbm<- pdata.frame(ocbm, index=c('id', 'time'))


bm_r<- pggls(form1, data=ocbm, model='pooling')
bm_r<- plm(form1, ocbm, index = c("id", "time"), model = "within")

summary(bm_r, vcov=vcovHC(bm_r, type="HC1"))
calc_stats_for_ols(summary(bm_r, vcov=vcovHC(bm_r, type="HC1")))


##### Getting AutoCorr
error_df = data.frame(bm_r$residuals)
colnames(error_df)<- 'residuals'
error_df$index = rownames(error_df)

ocbm<- input_df %>%
  mutate(index=rownames(input_df)) %>%
  left_join(error_df, 'index') %>%
  group_by('name', 'aircraft_type') %>%
  mutate(prev_val = lag(residuals, 1))
plot(as.numeric(ocbm$prev_val), as.numeric(ocbm$residuals), main='Auto Correlation in Residuals in BM3', xlab='Previous Residuals', ylab='Residuals')

```


## benchmark case 4:

```{r}
input_df<- panel_df
form1<- ln_fuel ~ ln_number_of_flights + ln_airborne_hours + ln_payload + ln_distance + as.factor(quater) + ln_average_fuel_price + ln_fuel_price_t_minus_1 + ln_fuel_price_t_minus_2 + ln_fuel_price_t_minus_3

# Check if using OLS vs GLS
bm<- plm(form1, data=input_df)
bptest(bm)

# Check if FE vs RE
phtest(form1, input_df)
bm_r<- pggls(form1, data=input_df, model='pooling')
bm_r<- plm(form1, input_df, index = c("id", "time"), model = "within")

# Check if needing OC correction
dwtest(form1, data=input_df)

# Implement OC correction
error_df = data.frame(bm_r$residuals)
colnames(error_df)<- 'residuals'
error_df$index = rownames(error_df)

ocbm<- input_df %>%
  mutate(index=rownames(input_df)) %>%
  left_join(error_df, 'index') %>%
  group_by('name', 'aircraft_type') %>%
  mutate(prev_val = lag(residuals, 1),
         ln_fuel_lag = lag(ln_fuel, 1),
         ln_number_of_flights_lag = lag(ln_number_of_flights, 1),
         ln_airborne_hours_lag = lag(ln_airborne_hours, 1),
         ln_payload_lag = lag(ln_payload, 1),
         ln_distance_lag = lag(ln_distance, 1),
         ln_average_fuel_price_lag = lag(ln_average_fuel_price, 1),
         ln_fuel_price_t_minus_1_lag = lag(ln_fuel_price_t_minus_1, 1),
         ln_fuel_price_t_minus_2_lag = lag(ln_fuel_price_t_minus_2, 1),
         ln_fuel_price_t_minus_3_lag = lag(ln_fuel_price_t_minus_3, 1))

oc_correct_lm_bm<- lm(residuals~prev_val - 1, data=ocbm)
rbm<- oc_correct_lm_bm$coefficients

ocbm<- ocbm %>%
  mutate(ln_fuel = ln_fuel - rbm * ln_fuel_lag, 
         ln_number_of_flights = ln_number_of_flights - rbm * ln_number_of_flights_lag,
         ln_airborne_hours = ln_airborne_hours - rbm * ln_airborne_hours_lag,
         ln_payload = ln_payload - rbm * ln_payload_lag,
         ln_distance = ln_distance - rbm * ln_distance_lag,
         ln_average_fuel_price = ln_average_fuel_price - rbm * ln_average_fuel_price_lag,
         ln_fuel_price_t_minus_1 = ln_fuel_price_t_minus_1 - rbm * ln_fuel_price_t_minus_1_lag,
         ln_fuel_price_t_minus_2 = ln_fuel_price_t_minus_2 - rbm * ln_fuel_price_t_minus_2_lag,
         ln_fuel_price_t_minus_3 = ln_fuel_price_t_minus_3 - rbm * ln_fuel_price_t_minus_3_lag)

ocbm<- pdata.frame(ocbm, index=c('id', 'time'))


bm_r<- pggls(form1, data=ocbm, model='pooling')
bm_r<- plm(form1, ocbm, index = c("id", "time"), model = "within")

summary(bm_r, vcov=vcovHC(bm_r, type="HC1"))

calc_stats_for_ols(summary(bm_r, vcov=vcovHC(bm_r, type="HC1")))


```


## benchmark case 5:

```{r}
input_df<- panel_df
form1<- ln_fuel ~ ln_number_of_flights + ln_airborne_hours + ln_payload + ln_distance + as.factor(quater) + ln_average_fuel_price + ln_fuel_price_t_minus_1 + ln_fuel_price_t_minus_2 + ln_fuel_price_t_minus_3 + ln_fuel_price_t_minus_4

# Check if using OLS vs GLS
bm<- plm(form1, data=input_df)
bptest(bm)

# Check if FE vs RE
phtest(form1, input_df)
bm_r<- pggls(form1, data=input_df, model='pooling')
bm_r<- plm(form1, input_df, index = c("id", "time"), model = "within")

# Check if needing OC correction
dwtest(form1, data=input_df)

# Implement OC correction
error_df = data.frame(bm_r$residuals)
colnames(error_df)<- 'residuals'
error_df$index = rownames(error_df)

ocbm<- input_df %>%
  mutate(index=rownames(input_df)) %>%
  left_join(error_df, 'index') %>%
  group_by('name', 'aircraft_type') %>%
  mutate(prev_val = lag(residuals, 1),
         ln_fuel_lag = lag(ln_fuel, 1),
         ln_number_of_flights_lag = lag(ln_number_of_flights, 1),
         ln_airborne_hours_lag = lag(ln_airborne_hours, 1),
         ln_payload_lag = lag(ln_payload, 1),
         ln_distance_lag = lag(ln_distance, 1),
         ln_average_fuel_price_lag = lag(ln_average_fuel_price, 1),
         ln_fuel_price_t_minus_1_lag = lag(ln_fuel_price_t_minus_1, 1),
         ln_fuel_price_t_minus_2_lag = lag(ln_fuel_price_t_minus_2, 1),
         ln_fuel_price_t_minus_3_lag = lag(ln_fuel_price_t_minus_3, 1),
         ln_fuel_price_t_minus_4_lag = lag(ln_fuel_price_t_minus_4, 1))

oc_correct_lm_bm<- lm(residuals~prev_val - 1, data=ocbm)
rbm<- oc_correct_lm_bm$coefficients


ocbm<- ocbm %>%
  mutate(ln_fuel = ln_fuel - rbm * ln_fuel_lag, 
         ln_number_of_flights = ln_number_of_flights - rbm * ln_number_of_flights_lag,
         ln_airborne_hours = ln_airborne_hours - rbm * ln_airborne_hours_lag,
         ln_payload = ln_payload - rbm * ln_payload_lag,
         ln_distance = ln_distance - rbm * ln_distance_lag,
         ln_average_fuel_price = ln_average_fuel_price - rbm * ln_average_fuel_price_lag,
         ln_fuel_price_t_minus_1 = ln_fuel_price_t_minus_1 - rbm * ln_fuel_price_t_minus_1_lag,
         ln_fuel_price_t_minus_2 = ln_fuel_price_t_minus_2 - rbm * ln_fuel_price_t_minus_2_lag,
         ln_fuel_price_t_minus_3 = ln_fuel_price_t_minus_3 - rbm * ln_fuel_price_t_minus_3_lag,
         ln_fuel_price_t_minus_4 = ln_fuel_price_t_minus_4 - rbm * ln_fuel_price_t_minus_4_lag)

ocbm<- pdata.frame(ocbm, index=c('id', 'time'))

bm_r<- pggls(form1, data=ocbm, model='pooling')
bm_r<- plm(form1, ocbm, index = c("id", "time"), model = "within")

summary(bm_r, vcov=vcovHC(bm_r, type="HC1"))
calc_stats_for_ols(summary(bm_r, vcov=vcovHC(bm_r, type="HC1")))


```





