# Import Data & Data Cleaning

## Load required libraries

```{r}
library(tidyverse)
```


```{r}
library(plm)
library(readxl)
library(fastDummies)
library(car)
```

## Data Cleaning

```{r}
df<- read_xlsx('database2010_2019_Febcorrect3.xlsx') %>%
        select(AIRCRAFT_TYPE, ln_AIR_FUELS_ISSUED,
        ln_DEPARTURES_SCHEDULED, ln_AIR_TIME, ln_DISTANCE,
        time, AIRLINE_ID) %>%
  dplyr::mutate(AIRCRAFT_TYPE=dplyr::recode(AIRCRAFT_TYPE, '612'='B737-700', '614'='B737-800', '634'='B737-900','698'='A319', '694'='A320', '622'='B757-200','626'='B767-300', '627'='B777','637'='B777')) %>%
  group_by(AIRCRAFT_TYPE, time, AIRLINE_ID) %>%
  summarise(ln_AIR_FUELS_ISSUED = log(sum(exp(ln_AIR_FUELS_ISSUED))),
            ln_DEPARTURES_SCHEDULED = log(sum(exp(ln_DEPARTURES_SCHEDULED))),
            ln_AIR_TIME = log(sum(exp(ln_AIR_TIME))),
            ln_DISTANCE = log(sum(exp(ln_DISTANCE))))

# '721'='A321'
# df<- read_xlsx('database2010_2019_all.xlsx') %>%
#   select(AIRCRAFT_TYPE, ln_AIR_FUELS_ISSUED,
#         ln_DEPARTURES_SCHEDULED, ln_AIR_TIME,
#         time, AIRLINE_ID) %>%
#   mutate(AIRCRAFT_TYPE=recode(AIRCRAFT_TYPE, '622'='B757-200', '627'='B777','637'='B777','339'='A330', '343'='A330','824'='A330','359'='A350','836'='A350','882'='A380'))

# wide body


df <- subset(df, !is.na(AIRCRAFT_TYPE))

```



```{r}


# Load ppi data and recode the month into quarters and calculate the inflation rate (ratio)
ppi<- read_csv('ppi.csv') %>%
  pivot_longer(-Year, names_to = 'Month', values_to = 'ppi') %>%
  mutate(quarter=ifelse(Month %in% c('Jan', 'Feb', 'Mar'), 'Q1', 
                        ifelse(Month %in% c('Apr', 'May', 'Jun'), 'Q2',
                               ifelse(Month %in% c('Jul', 'Aug', 'Sep'), 'Q3', 'Q4')))) %>%
  group_by(Year, quarter) %>%
  summarise(ppi=mean(ppi)) %>%
  arrange(Year, quarter) %>%
  ungroup() %>%
  mutate(time=row_number(),
         ratio=ppi/173)

# Load fuel price
fuel_price<- read_xlsx('all_flights_fuel.xlsx') %>% 
  select(time,`ln_Average_Fuel_Price (Dollar per gallon)`) %>%
  unique()

# Merge all data set together and calculate the aggregated y and x variables
aggregated_data <- df %>%
  left_join(fuel_price, by='time') %>%
  left_join(ppi %>% select(time, ratio), 'time') %>%
  mutate(`ln_Average_Fuel_Price (Dollar per gallon)` = log(exp(`ln_Average_Fuel_Price (Dollar per gallon)`) / ratio))
```



```{r}
aircraft_counts <- aggregated_data %>%
  group_by(AIRCRAFT_TYPE) %>%
  summarise(Count = n())
aircraft_counts
```



```{r}
# Recode column names
colnames(aggregated_data)<- c('aircraft_type', 'time' ,'airline_id', 'ln_fuel', 'ln_number_of_flights', 'ln_airborne_hours', 'ln_distance', 'ln_average_fuel_price', 'ratio')
aggregated_data <- subset(aggregated_data, select = -c(ratio))
aggregated_data
```

```{r}
# for(i in 1:8){
#   ln_fuel_i<- aggregated_data %>%
#     mutate(time=time+i, fpt=ln_average_fuel_price) %>%
#     select(aircraft_type, time, fpt) %>%
#     unique()
#
#   aggregated_data<- aggregated_data %>%
#     left_join(ln_fuel_i, by=c('aircraft_type','time'))
# }

# aggregated_data<- aggregated_data %>%
#   mutate(quater = ifelse(time%%4==0, 4, time%%4))
# colnames(aggregated_data)[10:length(colnames(aggregated_data))-1] <- unlist(lapply(1:8, function(x) paste0('ln_fuel_price_t_minus_', x)))

# Create lag for x and y
# lead<- dplyr::lead
# lag<- dplyr::lag
# aggregated_data_change<- aggregated_data %>%
#   group_by(aircraft_type) %>%
#   mutate(ln_fuel_change = exp(ln_fuel) - exp(lag(ln_fuel)),
#          ln_num_of_flights_change = exp(ln_number_of_flights) - exp(lag(ln_number_of_flights)),
#          ln_airborne_hours_change = exp(ln_airborne_hours) - exp(lag(ln_airborne_hours)),
#          ln_average_fuel_price_change = exp(ln_average_fuel_price) - lag(lead(ln_average_fuel_price)))
```

```{r}
for(i in 1:8){
  ln_fuel_i<- aggregated_data %>%
    mutate(time=time+i, fpt=ln_average_fuel_price) %>%
    select(aircraft_type, time, fpt) %>%
    unique()

  aggregated_data<- aggregated_data %>%
    left_join(ln_fuel_i, by=c('aircraft_type','time'))
}

aggregated_data<- aggregated_data %>%
  mutate(quater = ifelse(time%%4==0, 4, time%%4))
colnames(aggregated_data)[10:length(colnames(aggregated_data))-1] <- unlist(lapply(1:8, function(x) paste0('ln_fuel_price_t_minus_', x)))

# Create lag for x and y
lead<- dplyr::lead
lag<- dplyr::lag
aggregated_data_change<- aggregated_data %>%
  dplyr::group_by(aircraft_type) %>%
  dplyr::mutate(ln_fuel_change = exp(ln_fuel) - exp(lag(ln_fuel)),
         ln_num_of_flights_change = exp(ln_number_of_flights) - exp(lag(ln_number_of_flights)),
         ln_airborne_hours_change = exp(ln_airborne_hours) - exp(lag(ln_airborne_hours)),
         ln_average_fuel_price_change = exp(ln_average_fuel_price) - lag(lead(ln_average_fuel_price)))
```

```{r}
airline_id<- read_csv('airline_id.csv')
colnames(airline_id)<- c('airline_id', 'name')
  
aggregated_data<- airline_id %>% 
  right_join(aggregated_data, by='airline_id')

names<- unlist(strsplit(aggregated_data$name, ': '))
names<- names[seq(2, length(names),2)]
names<- substr(names,1,2)


aggregated_data$name<- as.factor(names)
```
```{r}
fuel_lag<- colnames(aggregated_data)[10:17]
aggregated_data
```

```{r}
# Install and load the required package if not already installed
install.packages("lmtest")
library(lmtest)

# Assuming 'model' is your linear regression model
# You can directly pass your model object to dwtest()
durbin_watson_test <- dwtest(m5)

# View the test results
print(durbin_watson_test)


```



# Regression

```{r}
# regression with interaction

m1<- lm(formula = ln_fuel ~ ln_number_of_flights + ln_airborne_hours + ln_average_fuel_price  + 
           as.factor(aircraft_type) + ln_fuel_price_t_minus_2, data=aggregated_data)
summary(m1)
```

```{r}
r_square<- numeric(0)
columns<- unlist(lapply(1:8, function(x) paste0('ln_fuel_price_t_minus_', x)))
for(i in 1:length(columns)){
  formula<- as.formula(paste(c(formula(m1), columns[i]), collapse = " + "))
  model<- lm(formula=formula, data=aggregated_data)
  results<- summary(model)$adj.r.squared
  r_square<- c(r_square, results)
}

```



## Stepwise Regression
```{r}
data_for_step<- aggregated_data %>% 
  select(-one_of(c('airline_id', 'name', 'ln_distance', 'time', 'quater',
                   'ln_fuel_price_t_minus_5', 'ln_fuel_price_t_minus_6', 'ln_fuel_price_t_minus_7', 'ln_fuel_price_t_minus_8'))) %>%
  na.omit()
step_model <- step(lm(ln_fuel ~ ., data = data_for_step), direction = "backward")
summary(step_model)

```

## Tests on the stepwise regression output

```{r}


m1<- lm(formula = ln_fuel ~ ln_number_of_flights + ln_airborne_hours  + 
           as.factor(aircraft_type) + ln_average_fuel_price + ln_fuel_price_t_minus_2, data=aggregated_data)
summary(m1)


outlier_removed<- aggregated_data[-c(485, 1758, 1760),]
m1_rm<- lm(formula = ln_fuel ~ ln_number_of_flights + ln_airborne_hours  + 
           as.factor(aircraft_type) + ln_average_fuel_price + ln_fuel_price_t_minus_2, data=outlier_removed) 
summary(m1_rm)
```


```{r}

panel_data<- aggregated_data %>%
  group_by(name, time) %>%
  summarise(ln_fuel = log(sum(exp(ln_fuel))),
            ln_number_of_flights = log(sum(exp(ln_number_of_flights))),
            ln_airborne_hours = log(sum(exp(ln_airborne_hours))),
            ln_average_fuel_price = mean(ln_average_fuel_price),
            ln_fuel_price_t_minus_2 = mean(ln_fuel_price_t_minus_2))

panel_data2<- aggregated_data %>%
  group_by(aircraft_type, time) %>%
  summarise(ln_fuel = log(sum(exp(ln_fuel))),
            ln_number_of_flights = log(sum(exp(ln_number_of_flights))),
            ln_airborne_hours = log(sum(exp(ln_airborne_hours))),
            ln_average_fuel_price = mean(ln_average_fuel_price),
            ln_fuel_price_t_minus_2 = mean(ln_fuel_price_t_minus_2))






panel_df<- pdata.frame(panel_data, index=c('name', 'time'))
m3<- pggls(ln_fuel ~ ln_number_of_flights + ln_airborne_hours + ln_average_fuel_price + ln_fuel_price_t_minus_2, data=panel_df, model='random')
phtest(ln_fuel ~ ln_number_of_flights + ln_airborne_hours + ln_average_fuel_price + ln_fuel_price_t_minus_2, data=panel_data)
summary(m3)


panel_df2<- pdata.frame(panel_data2, index=c('aircraft_type', 'time'))
m4<- pggls(ln_fuel ~ ln_number_of_flights + ln_airborne_hours + ln_average_fuel_price + ln_fuel_price_t_minus_2, data=panel_df2)
phtest(ln_fuel ~ ln_number_of_flights + ln_airborne_hours + ln_average_fuel_price + ln_fuel_price_t_minus_2, data=panel_data2)
summary(m4)
```

```{r}
aggregated_data_panel<- aggregated_data
aggregated_data_panel$id<- paste0(aggregated_data_panel$name, aggregated_data_panel$aircraft_type)
panel_df_3<- pdata.frame(aggregated_data_panel, index=c('id', 'time'))
m5<- pggls(ln_fuel ~ ln_number_of_flights + ln_airborne_hours + ln_average_fuel_price + ln_fuel_price_t_minus_2, data=panel_df_3)
summary(m5)
```






```{r}
w<- panel_df_3
w$key<- row.names(w)
a<- data.frame(resid(m5))
a$key<- row.names(a)

w <- w %>% left_join(a, by='key')

airline_results <- c()
dw_results <- c()
for(airline in unique(w$id)){
 
  selected_w<- w %>% filter(id == airline) %>% arrange(time)
  dw<- sum(diff(as.numeric(selected_w$resid.m5.))^2, na.rm=T) / sum(as.numeric(selected_w$resid.m5.)^2, na.rm=T)
  airline_results <- c(airline_results, airline)
  dw_results <- c(dw_results, dw)
    
  
}
dw_results_df <- data.frame(
  airline = airline_results,
  durbin_watson_statistic = dw_results
)

```


```{r}
w<- panel_df2
w$key<- row.names(w)
a<- data.frame(resid(m4))
a$key<- row.names(a)

w <- w %>% left_join(a, by='key')

aircraft_results <- c()
dw_results <- c()
for(aircraft in unique(w$aircraft_type)){
 
  selected_w<- w %>% filter(aircraft_type == aircraft) %>% arrange(time)
  dw<- sum(diff(as.numeric(selected_w$resid.m4.))^2, na.rm=T) / sum(as.numeric(selected_w$resid.m4.)^2, na.rm=T)
  aircraft_results <- c(aircraft_results, aircraft)
  dw_results <- c(dw_results, dw)
    
  
}
dw_results_df <- data.frame(
  aircraft = aircraft_results,
  durbin_watson_statistic = dw_results
)


```






```{r}
# Obtain residuals from the model
residuals <- resid(m1)

# Fitted values
fitted_values <- fitted(m1)

# Plot residuals vs fitted values
plot(fitted_values, residuals, 
     xlab = "Fitted Values", ylab = "Residuals",
     main = "Residuals vs Fitted Values Plot")
abline(h = 0, col = "red")  # Add a horizontal line at y = 0 for reference




```










```{r}

formula7<- ln_fuel ~  ln_number_of_flights + ln_airborne_hours + ln_average_fuel_price + as.factor(aircraft_type) + as.factor(name)
m7<- lm(formula = formula7, data=aggregated_data)
summary(m7)
formula8<- ln_fuel ~ ln_number_of_flights + ln_airborne_hours +  as.factor(aircraft_type):ln_average_fuel_price + as.factor(name) +  as.factor(aircraft_type)

```

```{r}

formula10<- ln_fuel ~ ln_number_of_flights + ln_airborne_hours +  as.factor(aircraft_type)
m10<- lm(formula = formula10, data=aggregated_data)
summary(m10)

```

```{r}

formula8<- ln_fuel ~ ln_number_of_flights + ln_airborne_hours +  as.factor(aircraft_type):ln_average_fuel_price +  as.factor(aircraft_type)
m8<- lm(formula = formula8, data=aggregated_data)
summary(m8)

```

```{r}

formula9<- ln_fuel ~ ln_number_of_flights + ln_airborne_hours   + ln_fuel_price_t_minus_4+  as.factor(aircraft_type) + as.factor(name) 
m9<- lm(formula = formula9, data=aggregated_data)
summary(m9)

```


```{r}

formula10<- ln_fuel ~ ln_number_of_flights + ln_airborne_hours +  ln_distance + as.factor(aircraft_type) 
m10<- lm(formula = formula10, data=aggregated_data)
summary(m10)

```

```{r}

formula11<- ln_fuel ~ ln_number_of_flights + ln_airborne_hours +  ln_distance + ln_average_fuel_price : as.factor(aircraft_type) 
m11<- lm(formula = formula11, data=aggregated_data)
summary(m11)

```


### take out the uninteracted term
### add airline effect
  
```{r}

w = aggregated_data %>%
  mutate(hours = exp(ln_airborne_hours), fuel=exp(ln_fuel)) %>%
  mutate(fuel_per_hour = fuel/hours)

ggplot(data=w%>%filter(aircraft_type %in% c('A319', 'A320')), aes(x=aircraft_type, y=fuel_per_hour)) +
  geom_boxplot()

```

```{r}

formula12<- ln_fuel ~ ln_number_of_flights + ln_airborne_hours +  ln_distance: as.factor(aircraft_type) 
m12<- lm(formula = formula12, data=aggregated_data)
summary(m12)

```






